# Generated by Django 4.2.6 on 2023-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('usuario', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=12)),
                ('direction', models.CharField(max_length=64)),
            ],
        ),
    ]
